name = "Vision"
uuid = "9150dba0-62ab-4b8c-b7d2-25a0d6dd685f"
authors = ["Joshua Niemelä <josh@jniemela.dk>"]
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
HTTP = "^1.5"
JSON = "^0.21"
URIs = "^1.4"
julia = "1.8"
